### ISSUE TITLE
[Feature request]: Get new messages on re-run by default

### ISSUE THREAD

**Issue by andrewferguson** [clr2of8/SlackExtract#2]
When I re-run Invoke-SlackExtract after having previously run it before, I get several messages of the form:
`Skipping message download for [...]. Remove this file to force re-download: [...] meta/channels_meta/done_getting_messages_for.txt`

I then need to manually remove that file if I want to get any new messages.

I'm curious as to why this is the default behaviour. My initial thought was that this could be because otherwise the script might re-download everything (which would be wasteful), but when I re-run the script with the file removed, it downloads all new messages but doesn't seem to overwrite existing messages (so I guess my hypothesis was wrong?).

My goal is to create an archive of a slack channel, re-running the script every week or so to get the latest messages whilst keeping the oldest messages (which are now past the >10,000 limit) intact.

(Fantastic script by the way!)

**Comment by clr2of8** [comment]
Sorry for the late reply. I just barely got github notification setup properly so that I can see issues posted. I can add an option for you to force overwriting.

**Comment by andrewferguson** [comment]
As noted in my reply to #3 , I've modified a local fork of SlackExtract to do this. I can submit a PR for those changes but before I do I wondered if you had any thoughts on how the workflow for this would work.

My use of the script is to keep an archive of a Slack workspace that can continually evolve as more messages are posted to the Slack, even when the 10,000 message limit forces old messages to no longer be visible through the Slack web interface. That way I can run the script regularly (I put it in a cron job), and get a full archive of the workspace.

What I did was modify the script so that it overwrites *everything* each time it is run, but doesn't proactively delete things. This means things like new messages are downloaded, modified* messages are updated, and old messages that are past the 10,000 limit and therefore no longer accessible through the API are preserved in the archive. (I did investigate the possibility of checking to see if the message to be downloaded was modified compared to an existing version, but came to the conclusion that just overwriting everything was quicker. This probably won't be efficient if the workspace has heavy usage of large attachments - maybe I could add a separate check before overwriting attachments with an identical version?).

Do you think a flag that made the script behave as above would be a good approach?

\* *modified* messages include both ones that have been manually edited by the author, as well as automatic edits made by Slack to update the list of replies to that message. In my experience, the latter is far more common.

**Comment by clr2of8** [comment]
I would like to keep the default to where it doesn't overwrite for the
reason that enterprise workspaces don't have message limits and it can take
many days to download all of the data. But I'm happy to have a switch added
that causes it to execute the way you describe for your needs.
