### ISSUE TITLE
[Feature Request]: Support extracting message replies

### ISSUE THREAD

**Issue by andrewferguson** [clr2of8/SlackExtract#3]
The current version of the script does not appear to extract replies to messages on Slack. It would be really great if support for extracting message replies could be added!

**Comment by clr2of8** [comment]
Thank you for the idea. If I can get to it I'll add it or if someone else wants to PR :)

**Comment by andrewferguson** [comment]
I actually added this in my own (local) fork of SlackExtract (along with other features such as a fix for #2 and support for downloading profile images). Hacktoberfest is a good motivator to get my code cleaned up and upstreamed before the end of October. I'll look into cleaning it up submitting some more PRs this weekend.

**Comment by clr2of8** [comment]
perfect! thank you. I haven't needed to use my script for many months so I
haven't been actively looking at it. I look forward to your PRs
